//
//  RaidSlug+OpenAPI.swift
//  RaiderIOAPI
//
//  Generated by extract-slugs.sh - do not edit directly.
//

public extension RaidSlug {

    static let aberrusTheShadowedCrucible: RaidSlug = "aberrus-the-shadowed-crucible"
    static let amirdrassilTheDreamsHope: RaidSlug = "amirdrassil-the-dreams-hope"
    static let antorusTheBurningThrone: RaidSlug = "antorus-the-burning-throne"
    static let awakenedAberrusTheShadowedCrucible: RaidSlug = "awakened-aberrus-the-shadowed-crucible"
    static let awakenedAmirdrassilTheDreamsHope: RaidSlug = "awakened-amirdrassil-the-dreams-hope"
    static let awakenedVaultOfTheIncarnates: RaidSlug = "awakened-vault-of-the-incarnates"
    static let battleOfDazaralor: RaidSlug = "battle-of-dazaralor"
    static let blackrockDepths: RaidSlug = "blackrock-depths"
    static let castleNathria: RaidSlug = "castle-nathria"
    static let crucibleOfStorms: RaidSlug = "crucible-of-storms"
    static let fatedCastleNathria: RaidSlug = "fated-castle-nathria"
    static let fatedSanctumOfDomination: RaidSlug = "fated-sanctum-of-domination"
    static let fatedSepulcherOfTheFirstOnes: RaidSlug = "fated-sepulcher-of-the-first-ones"
    static let liberationOfUndermine: RaidSlug = "liberation-of-undermine"
    static let manaforgeOmega: RaidSlug = "manaforge-omega"
    static let nerubarPalace: RaidSlug = "nerubar-palace"
    static let nyalothaTheWakingCity: RaidSlug = "nyalotha-the-waking-city"
    static let sanctumOfDomination: RaidSlug = "sanctum-of-domination"
    static let sepulcherOfTheFirstOnes: RaidSlug = "sepulcher-of-the-first-ones"
    static let sporefall: RaidSlug = "sporefall"
    static let theEmeraldNightmare: RaidSlug = "the-emerald-nightmare"
    static let theEternalPalace: RaidSlug = "the-eternal-palace"
    static let theNighthold: RaidSlug = "the-nighthold"
    static let theTideboundGrotto: RaidSlug = "the-tidebound-grotto"
    static let theVenomousAbyss: RaidSlug = "the-venomous-abyss"
    static let tierMn1: RaidSlug = "tier-mn-1"
    static let tombOfSargeras: RaidSlug = "tomb-of-sargeras"
    static let trialOfValor: RaidSlug = "trial-of-valor"
    static let uldir: RaidSlug = "uldir"
    static let vaultOfTheIncarnates: RaidSlug = "vault-of-the-incarnates"

}
