#!/bin/bash

set -euo pipefail

OPENAPI_FILE="Sources/RaiderIOAPI/openapi.json"
OUTPUT="Sources/RaiderIOAPI/RaidSlug+OpenAPI.swift"

SLUGS=$(jq '.components.schemas.OverallRaidProgression.properties | keys' "$OPENAPI_FILE")

echo "Region slugs:"
echo $SLUGS | jq

{
    cat <<'EOF'
//
//  RaidSlug+OpenAPI.swift
//  RaiderIOAPI
//
//  Generated by extract-slugs.sh - do not edit directly.
//

public extension RaidSlug {

EOF

    echo "$SLUGS" | jq -r '
        def toCamel: [splits("-")] | .[0] + ( .[1:] | map( (.[0:1] | ascii_upcase) + .[1:] ) | join("") );
        .[] | "    static let \(toCamel): RaidSlug = \"\(.)\""
    '

    cat <<'EOF'

}
EOF
} > "$OUTPUT"
