name: Update OpenAPI definition

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

env:
  OPENAPI_FILE: Sources/RaiderIOAPI/openapi.json

jobs:
  upgrade:
    name: Upgrade OpenAPI definition
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Current definition version
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .info.version "$OPENAPI_FILE"

      - name: Fetch OpenAPI definition
        run: ./scripts/update-openapi-definition.sh

      - name: Extract slugs
        run: ./scripts/extract-slugs.sh

      - name: New definition version
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .info.version "$OPENAPI_FILE"

      - name: Verify schema was updated
        id: verify-changes
        uses: tj-actions/verify-changed-files@v16
        with:
          files: |
            "$OPENAPI_FILE"

      - name: Commit version change # TODO: commit on separate branch and create PR on GitHub for this
        if: steps.verify-changes.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(api): update Raider.IO OpenAPI definition"
